modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Zero"

[[mods]]
modId="tiger_test"
version="1.0"
displayName="Tiger test 1.0"
credits="By ME"
authors="Orbit ig for now"

[[dependencies.tiger_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




